### PR TITLE
Add Fediverse-Files video to the readme

### PR DESCRIPTION
**Pull request by pfefferle**
What about adding the fediverse files video to the readme?

I think it might help to understand the idea?

### CODE REVIEW

**Comment by davemart-in** [comment]
Totally optional, but if you want, you could embed a screenshot image of the video to draw more attention to it like this:

[image](https://www.youtube.com/watch?v=QzYozbNneVc)

We could even add the YouTube chrome at the bottom if you want.

Again, totally optional.

**Comment by pfefferle** [comment]
@davemart-in WordPress.org will directly embed the video, so I think there is no need to add an additional screenshot!?!

**Comment by pfefferle** [comment]
@davemart-in ah, you might mean the markdown file... maybe we add the image there to draw some attention to it... or maybe we find a way to embed it there too!!!

**Comment by davemart-in** [comment]
Yeah, sorry. I wasn't specific in my comment. Not sure you can embed a video in the Readme file, but you can use an image screenshot.

**Pull request merged**
