### PR TITLE
Add baseline tests for Post::get_type()

### PR DESCRIPTION
**Pull request by obenland**
Allows us to make changes with more confidence in the future.

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Go to '..'
*

### CODE REVIEW

**Comment by obenland** [comment]
@pfefferle I asked Claude.ai to create some unit tests for the `get_type()` method as it's written in trunk, so we can compare future changes with those outcomes.

It currently fails for posts without a post format (`test_get_type_handles_missing_post_format`), probably because of a wrong assumption? Posts with a title, more than 400 char content and no post format should be considered Articles, yes?

**Comment by pfefferle** [comment]
@obenland I would say so, yes.

**Review by pfefferle — APPROVED** [review]
You are using a different naming convention for the new test. I have no strong feelings about how we should name them, but I would vote for keeping them consistent, so we should work on a follow up PR that renames the other tests.

**Comment by obenland** [comment]
Yeah I got a phpcs error for the filename without the pre-pended `class-`. I'll do a follow up.

**Pull request merged**
