### PR TITLE
Anonymous function lint

### PR DESCRIPTION
**Pull request by mattwiebe**
This is what wpcom demands, apparently :)

### CODE REVIEW

**Review by pfefferle — APPROVED** [review]

**Comment by obenland** [comment]
[It's part of Core's PHP Coding Standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#closures-anonymous-functions).

How would you feel about requiring them for this plugin?

**Comment by pfefferle** [comment]
@obenland I thought we do that, I have no idea why this was not checked: https://github.com/Automattic/wordpress-activitypub/blob/master/phpcs.xml

**Comment by obenland** [comment]
So many exceptions! 😱

I'm not sure, it's been a while since I tried setting that up. Maybe all warnings need to elevated to errors for them to be blocked from going in? https://github.com/Automattic/wpcomsh/blob/trunk/phpcs.xml.dist#L35-L36

**Comment by pfefferle** [comment]
Yes, @mattwiebe worked quite some time on it, so that it is compatible with WP.com

**Comment by mattwiebe** [comment]
Those exceptions are mostly mimicking stuff I found on the wpcom side :)

**Pull request merged**
