### PR TITLE
doc: remove comma between subject and predicate

### PR DESCRIPTION
**Pull request by foxyseta**
## Proposed changes:

* doc: fix grammar error in README.md (comma between subject group and predicate group)

### Other information:

- [ ] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Reade README.md

### CODE REVIEW

**Comment by pfefferle** [comment]
Can you please change that in the txt version instead? The md version is auto generated.

**Comment by foxyseta** [comment]
Whoopsie, hadn't noticed that, sorry. Sure!

**Review by mattwiebe — APPROVED** [review]
Thanks @foxyseta - apologies for the delay!

**Comment by foxyseta** [comment]
No problem. Thank you!

**Pull request merged**
