### PR TITLE
Some CSS fixes for the reactions block

### LINKED ISSUE #1106: Reactions Block: link color conflicts with dark themes
### Quick summary

The links added in the Reactions block do not use the link colors defined within a block-based theme, so that can cause some contrast issues:

Image

Maybe they should stick to the theme's color scheme as much as possible, and then offer the core layout customization options if one wants to make any changes?

### Steps to reproduce

1. Start with a site running a block-based theme
2. Customize your theme to use a dark color scheme
3. Activate the ActivityPub plugin
4. Check the look of the Reactions block on your site's frontend

### What you expected to happen

I would expect the different elements of the block to match my theme's settings. 

### What actually happened

In the screenshot above, it shows that links are set to be yellow on my site, yet the reactions label is blue and the reaction item link is white.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by pfefferle**
This should fix the interference with the Webmention plugin and fix #1106

Can you maybe test the changes with your theme @jeherve ?

## Proposed changes:

Screenshot 2024-12-20 at 10 13 43
Screenshot 2024-12-20 at 10 13 58
Screenshot 2024-12-20 at 10 14 12
Screenshot 2024-12-20 at 10 14 28
Screenshot 2024-12-20 at 10 15 34

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
> Can you maybe test the changes with your theme @jeherve ?

It updated the main link color, but not the one in the modal:
image

You can see it live at https://herve.bzh/20241218-15277/

**Comment by pfefferle** [comment]
@jeherve Can you tell me the theme you are using?!

**Comment by jeherve** [comment]
> Can you tell me the theme you are using?!

That's [Hey](https://wordpress.org/themes/hey/).

I don't seem to notice a difference with your last push.

image

**Comment by obenland** [comment]
@jeherve When you get a chance, could you try again with ea8116e876454f2147b8c8861360844b7fc3fa98 now in place?

**Review by obenland — APPROVED** [review]

**Comment by jeherve** [comment]
> When you get a chance, could you try again with [ea8116e](https://github.com/Automattic/wordpress-activitypub/commit/ea8116e876454f2147b8c8861360844b7fc3fa98) now in place?

Sorry I was AFK, but can confirm that things look good now!

**Pull request merged**
