### PR TITLE
PHPCS: Enable UnusedFunctionParameter sniff

### PR DESCRIPTION
**Pull request by obenland**
## Proposed changes:

* Removes unused function parameters and their docs.
* Adds a unit test for `at_title` shortcode to make sure that still works.
* Removes sniff exception.

See #905.

### CODE REVIEW

**Comment by pfefferle** [comment]
won't that result in at least PHP warnings, because the functions are always called with these params, if they are used or not?

**Comment by obenland** [comment]
Yeah, maybe this needs a different approach

**Comment by obenland** [comment]
@pfefferle Can you double-check? I think they should just be ignored. I've also not been able to generate a warning in my testing.

**Comment by pfefferle** [comment]
OK, the shortcode API says:

> Three parameters are passed to the shortcode callback function. You can choose to use any number of them including none of them.

**Review by pfefferle — APPROVED** [review]

**Pull request merged**
