### PR TITLE
Version bump 4.4.0

### PR DESCRIPTION
**Pull request by obenland**
## Proposed changes:

* Bumps versions to 4.4.0

### CODE REVIEW

**Comment by pfefferle** [comment]
You have to add the links below and above the comment: https://github.com/Automattic/wordpress-activitypub/blob/d9a7c6677ca10313d4f089a81a1cff5bcaf77f1e/CHANGELOG.md?plain=1#L1129

**Comment by obenland** [comment]
I have never seen this before! 😄 (As in, never scrolled down that file far enough)

**Comment by pfefferle** [comment]
Because WordPress.org limits the size of the readme, you could also remove old changelog items. I would remove all `4.1.X` and below.

**Review by pfefferle — APPROVED** [review]
that's it!

**Pull request merged**
