### PR TITLE
Correct branding for WordPress in node info

### LINKED ISSUE #436: Feature Request: proper banding for "WordPress" in nodeinfo
### What

When viewing an account, some apps make it possible to see what sort of software the server is running. For example Mastodon, Pixelfed, Lemmy etc.

At the moment, users see "wordpress" all lower case:
Screenshot of an app where the server type is lower case.

### Why

This should be changed to "WordPress" (CamelCase) as per the [brand guidelines](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/).

The incoming pull request updates the server software name to:

Screenshot of an app where the server type is Camel Case case.

### How

This can easily be updated in 

https://github.com/Automattic/wordpress-activitypub/blob/f7ebced6245c2422efea10430cd7ea68ec0c0c56/includes/rest/class-nodeinfo.php#L83

### PR DESCRIPTION
**Pull request by edent**
Fixes #436 

## Proposed changes:

* Displays the correct CamelCase when users view a profile.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Visit a users profile. Their server type is currently "wordpress".
* Apply patch. Their server type is now "WordPress"
* Enter the weekend with the satisfaction that the branding team aren't going to shout at you.

### CODE REVIEW

**Comment by pfefferle** [comment]
I think this is more meant to be a slug. The spec uses only lowercase ids: http://nodeinfo.diaspora.software/schema.html

Some other examples:

* Mastodon https://mastodon.social/nodeinfo/2.0
* Pixelfed https://pixelfed.social/api/nodeinfo/2.0.json
* Lemmy https://lemmy.ml/nodeinfo/2.0.json

**Comment by edent** [comment]
Well, you're not wrong! I could have sworn I saw some with mixed case - but I can't find any now.

This PR violates the spec (`/^[a-z0-9-]+$/`) but worked on my app.

I'll raise an issue with NodeInfo project.

**Comment by pfefferle** [comment]
I am not sure if it is a good idea to change it, because then you have to fight with exactly the issue you mentioned: How do you correctly write a Product name

In the current version you only have to know how it is spelled.

So maybe this is more an issue that has to be solved on the platforms itself!?!

**Comment by pfefferle** [comment]
I will close this for now https://github.com/jhass/nodeinfo/issues/67

**Pull request closed without merging**
