### PR TITLE
Improve lemmy compatibility

### PR DESCRIPTION
**Pull request by pfefferle**
Improve the compatibility with lemmy! Thanks @Nutomic for the feedback https://socialhub.activitypub.rocks/t/discourse-wordpress-integration/4162/13?u=pfefferle

### CODE REVIEW

**Comment by Nutomic** [comment]
That's great! You can test it with voyager.lemmy.ml which has the latest changes deployed.

**Comment by pfefferle** [comment]
@Nutomic can you approve my request?

**Comment by Nutomic** [comment]
Ive approved it.

**Comment by pfefferle** [comment]
@Nutomic I messed up my password and it seems to not send password reminder 🫣

**Comment by Nutomic** [comment]
It should be able to send emails, maybe it went to spam? Otherwise just register another account.

**Comment by pfefferle** [comment]
made a second account

**Comment by pfefferle** [comment]
@Nutomic OK, seems to work, at least following, but posts seems to not be federated properly?!?

Here is an example JSON: https://pfefferle.org/hello-lemmy-part2/?activitypub

**Comment by pfefferle** [comment]
All test posts here: https://pfefferle.org/

You can add `?activitypub` at the end of each post to see the JSON.

**Comment by pfefferle** [comment]
I will try to debug the Lemmy response later today!

**Comment by pfefferle** [comment]
FYI: The post will be federated by the User and Announced by the Group. But the Announce Object is only the Link to the Post, is that supported by Lemmy or does it need the full object as the Announce object?

**Comment by pfefferle** [comment]
@Nutomic the request is:

```
{
    "@context": [
        "https:\/\/www.w3.org\/ns\/activitystreams"
    ],
    "id": "https:\/\/pfefferle.org\/lemmy-part-4\/#activity",
    "type": "Announce",
    "published": "2024-05-03T12:32:29Z",
    "updated": "2024-05-06T08:03:39Z",
    "to": [
        "https:\/\/www.w3.org\/ns\/activitystreams#Public",
        "https:\/\/pfefferle.org\/wp-json\/activitypub\/1.0\/actors\/0\/followers"
    ],
    "cc": [],
    "object": "https:\/\/pfefferle.org\/lemmy-part-4\/",
    "actor": "https:\/\/pfefferle.org\/@pfefferle.org"
}
```

The response is:

```
[body] => {"error":"unknown","message":""}
[response] => Array
   (
        [code] => 400
        [message] => Bad Request
   )
```

**Comment by pfefferle** [comment]
Tried it with object instead of URI, with the same result: Error 400

```
{
    "@context": [
        "https:\/\/www.w3.org\/ns\/activitystreams"
    ],
    "id": "https:\/\/pfefferle.org\/lemmy-part-4\/#activity#activity",
    "type": "Announce",
    "audience": "https:\/\/pfefferle.org\/@pfefferle.org",
    "published": "2024-05-03T12:32:29Z",
    "updated": "2024-05-06T08:20:33Z",
    "to": [
        "https:\/\/www.w3.org\/ns\/activitystreams#Public",
        "https:\/\/pfefferle.org\/wp-json\/activitypub\/1.0\/actors\/1\/followers"
    ],
    "cc": [],
    "object": {
        "id": "https:\/\/pfefferle.org\/lemmy-part-4\/#activity",
        "type": "Update",
        "audience": "https:\/\/pfefferle.org\/@pfefferle.org",
        "published": "2024-05-03T12:32:29Z",
        "updated": "2024-05-06T08:20:33Z",
        "to": [
            "https:\/\/www.w3.org\/ns\/activitystreams#Public",
            "https:\/\/pfefferle.org\/wp-json\/activitypub\/1.0\/actors\/1\/followers"
        ],
        "cc": [],
        "object": {
            "id": "https:\/\/pfefferle.org\/lemmy-part-4\/",
            "type": "Article",
            "attachment": [],
            "attributedTo": "https:\/\/pfefferle.org\/author\/pfefferle\/",
            "audience": "https:\/\/pfefferle.org\/@pfefferle.org",
            "content": "\u003Cp\u003EIdentifies one or more entities that represent the total population of entities for which the object can considered to be relevant. Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.          \u003C\/p\u003E",
            "contentMap": {
                "en": "\u003Cp\u003EIdentifies one or more entities that represent the total population of entities for which the object can considered to be relevant. Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.          \u003C\/p\u003E"
            },
            "name": "Lemmy (Part 4)",
            "published": "2024-05-03T12:32:29Z",
            "summary": "Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant. Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.Identifies one or more entities that represent the total population of entities for which the object [...]",
            "tag": [],
            "updated": "2024-05-06T08:20:33Z",
            "url": "https:\/\/pfefferle.org\/lemmy-part-4\/",
            "to": [
                "https:\/\/www.w3.org\/ns\/activitystreams#Public",
                "https:\/\/pfefferle.org\/wp-json\/activitypub\/1.0\/actors\/1\/followers"
            ],
            "cc": []
        },
        "actor": "https:\/\/pfefferle.org\/author\/pfefferle\/"
    },
    "actor": "https:\/\/pfefferle.org\/@pfefferle.org"
}
```

**Comment by Nutomic** [comment]
Right Lemmy only supports Announce with embedded object for now, no link. Ive thrown the last activity you sent into our tests and it passes just fine (after replacing `\/` with `/`).

Looking at voyager.lemmy.ml, it appears that you sent an activity with the same id `https://pfefferle.org/lemmy-part-4/#activity` three days ago already. That means Lemmy will reject it as duplicate. You need to generate a new activity id if you want to send something new.

**Comment by pfefferle** [comment]
OK, I have a working version now! 🎉

Screenshot 2024-05-07 at 12 30 21

@Nutomic any chance that Lemmy will support URI objects soon? I am not sure if it is a good idea to change the current implementation, because I fear to break something else... 🫣

**Comment by Nutomic** [comment]
> any chance that Lemmy will support URI objects soon? I am not sure if it is a good idea to change the current implementation, because I fear to break something else... 🫣

Unfortunately I wont be able to implement that anytime soon.

**Comment by pfefferle** [comment]
@Nutomic ok, then I will see how other platforms handle Announce objects, to get this merged.

**Comment by pfefferle** [comment]
@nutomic It seems that I receive a 400 error on the `Accept` I sent to lemmy (@pfefferle.org@pfefferle.org)

Can you maybe help with debugging?

**Comment by Nutomic** [comment]
I tried to follow that actor, and there seems to be an error because an activity with the same id was already received before. Lemmy rejects duplicates, so make sure you dont send the same activity id twice.

**Pull request merged**
