### PR TITLE
Unmark comments as spam (maybe needs an option?)

### PR DESCRIPTION
**Pull request by colinleroy**
Hi,
I've noticed comments from the Fediverse have a tendancy to get flagged as spam by Akismet. 
I think that's unfortunate as there - for now ? - a lot less chance that this is the case.

This PR unflags spam on these comments and mark them for moderation instead.

Hope this helps, and thanks for the nice plugin!

### CODE REVIEW

**Comment by pfefferle** [comment]
Hey @colinleroy thanks for your pull request! What does `comment_status = 0` represent? Shouldn't it be hold, so that the site admin can review the comment?

**Comment by colinleroy** [comment]
Hi! Yes, "0" is hold for moderation ("1" is published, and "spam" is spam)
Hope this helps :)

**Comment by colinleroy** [comment]
I should try to see if Akismet has some sort of log to explain its decision, I'm unsure it does. I'll tell you :)

**Comment by pfefferle** [comment]
I do not think akismet is moving the comment, because I do not use it and have also federated comments in spam. I think this is a core glitch.

**Comment by colinleroy** [comment]
Interesting! I'll try to do more checks if it can help

**Comment by pfefferle** [comment]
We are working with Akismet and AntispamBee to fix this issue, so I will close this for now.

**Pull request closed without merging**
