### PR TITLE
CLI: Remove unneeded translation functions

### PR DESCRIPTION
**Pull request by obenland**
Could someone double-check me on my logic? 

I don't think translations get processed in the context of WP CLI (meaning docs or function messages get returned translated) but I could be wrong.

## Proposed changes:

* Removes translation functions from CLI commands.
* Updates parameter docs for `$args` params.

### CODE REVIEW

**Comment by pfefferle** [comment]
No translations for CLI commands?

**Comment by pfefferle** [comment]
Yoast-SEO seems to use translations, but the majority seems not to use them: https://github.com/search?q=WP_CLI%3A%3Asuccess&type=code

**Comment by pfefferle** [comment]
The text seems to be translated (except the special-chars 🫣)...

Screenshot 2024-11-12 at 21 45 49

So the questions might be more like: do we want that? even more because it seems to be the only translated text!?!

**Comment by obenland** [comment]
Interesting! Good to know

> So the questions might be more like: do we want that? even more because it seems to be the only translated text!?!

Up to you, I don't have a strong opinion

**Comment by pfefferle** [comment]
I just wanted to write the same... I have no strong feelings on that one and am happy to remove them!

**Review by pfefferle — APPROVED** [review]

**Comment by pfefferle** [comment]
you already removed the one from the description, so let's be consistent!

**Pull request merged**
