### PR TITLE
Simple Remote-Reply endpoint.

### PR DESCRIPTION
**Pull request by pfefferle**
implements #864

Adds the remote-reply feature to WebFinger using the OStatus reply feature `http://ostatus.org/schema/1.0/subscribe`.

Also adds a hook, so that maybe the Friends plugin can hook into the Remote-Follow feature:

`\do_action( 'activitypub_interactions_follow', $uri, $object );`

/cc @akirk

### CODE REVIEW

**Review by mediaformat — COMMENTED** [review]
1st try I was sent to the login page, however after that I was returned to `/wp-admin`
2nd try (already logged-in) it worked like a charm!

**Comment by pfefferle** [comment]
Thanks for testing it @mediaformat !

I also checked the endpoint without a user session and the redirect after the login worked nicely for me!?!

Do you have a second factor or something that might interfere with the redirect?

**Comment by mediaformat** [comment]
No 2nd factors, but I can try it again!

**Comment by pfefferle** [comment]
any update on your tests @mediaformat ?

**Pull request merged**
