### PR TITLE
Don't send direct message notification for received public activities

### PR DESCRIPTION
**Pull request by akirk**
With 4.5.0, I started receiving direct message e-mails for things that are not direct messages:

Screenshot 2024-12-18 at 08 53 45

I added a unit test without a reply and fixed the if. I am not sure why it was tested to be both a reply and public and not just public.

### CODE REVIEW

**Review by pfefferle — APPROVED** [review]
thanks a lot @akirk

**Review by pfefferle — CHANGES_REQUESTED** [review]
I will add some more tests!

**Review by pfefferle — APPROVED** [review]
should be good to go without further changes!

**Comment by jeherve** [comment]
Thanks for the quick fix!

**Pull request merged**
