### PR TITLE
Lint: Try dotcom's set of sniffs

### PR DESCRIPTION
**Pull request by mattwiebe**
Probably worth investigating how Jetpack runs their phpcs setup as they're merging frequently into dotcom but this works reliably up and until latest PHP versions

```
composer install
composer run lint
```

### CODE REVIEW

**Comment by timnolte** [comment]
@mattwiebe yes the latest release of WPCS is not compatible with PHP 8.x, you need to use the `develop` branch if you want these to work with PHP 8.x.

**Comment by mattwiebe** [comment]
@timnolte thanks! Looks like [be96b19](https://github.com/Automattic/wordpress-activitypub/pull/364/commits/be96b19781e3cf38d500352359d04ac477b5f953) resolves it for me. :)

**Comment by mattwiebe** [comment]
Although 3512206d4884e89cf7708be8a5b836388517ceeb brings us into conformance with the new set of sniffs, it also appears overall _more_ strict than what I was seeing on the wpcom side. In any case these seem good.

**Review by pfefferle — APPROVED** [review]
LGTM

thanks @mattwiebe and @timnolte

**Pull request merged**
