### PR TITLE
Fix styles in Follow-Me block

### PR DESCRIPTION
**Pull request by Menrath**
A `line-height` of `1` can easily hide some parts of letters like "g" or "p" which makes the actor-handle difficult to read.

The line height might even be up to 1.5, haven't investigated in best practices.

Example at: https://event-federation.eu/project/

### CODE REVIEW

**Review by mattwiebe — DISMISSED** [review]
Seems fine!

**Comment by pfefferle** [comment]
@mattwiebe can you re-build the CSS and push it to this PR?

**Comment by mattwiebe** [comment]
> @mattwiebe can you re-build the CSS and push it to this PR?

Done! Got to learn how to use [GitHub CLI](https://cli.github.com) to [check out a forked PR locally](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally) to do so.

**Review by pfefferle — APPROVED** [review]
LGTM

**Pull request merged**
