### PR TITLE
Actors: deprecate `as User_Collection` throughout

### PR DESCRIPTION
**Pull request by mattwiebe**
Deprecate `Activitypub\Collection\Actors as User_Collection` to simply use `Actors` throughout the codebase.

## Proposed changes:
* renamed `Users_Collection` to simply use `Actors`

### Other information:

- [x] Have you written new tests for your changes, if applicable? (not applicable, everything should be the same)

## Testing instructions:
Tests should pass, everything normal in function

### CODE REVIEW

**Comment by pfefferle** [comment]
I think we should also update `Actors::APPLICATION_USER_ID` then!?!

**Comment by mattwiebe** [comment]
> I think we should also update `Actors::APPLICATION_USER_ID` then!?!

Good idea!

**Comment by pfefferle** [comment]
@mattwiebe and don't forget the changelog ;)

**Comment by Menrath** [comment]
@mattwiebe @pfefferle I still have some doubts about this change, as the current `Actors::BLOG_USER_ID` and `Actors::APPLICATION_USER_ID` wordings show that the actors are indeed "mapped" to pseudo users. With a constant named `Actors::BLOG_ACTOR_ID` I would expect it more likely to be the full URI.

**Comment by mattwiebe** [comment]
> @mattwiebe @pfefferle I still have some doubts about this change, as the current `Actors::BLOG_USER_ID` and `Actors::APPLICATION_USER_ID` wordings show that the actors are indeed "mapped" to pseudo users. With a constant named `Actors::BLOG_ACTOR_ID` I would expect it more likely to be the full URI.

Interesting! I guess we do have to show the seams of Actors <-> Users mapping somewhere, and this may be as good a place as any.

**Review by pfefferle — APPROVED** [review]

**Pull request merged**
