### PR TITLE
have a filter to defer signature verification

### PR DESCRIPTION
**Pull request by pfefferle**
With the filter, you can defer (bypass) the signature verification based on the request parameters.

Maybe a quick win for #554

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Go to '..'
*

### CODE REVIEW

**Comment by mediaformat** [comment]
I wonder if this should be paired with something like WP_DEBUG_DISPLAY, to make it really obvious that this is active and debug related.

**Comment by pfefferle** [comment]
Good point!

**Comment by pfefferle** [comment]
I changed it to a filter, to also address #554

What do you think @mattwiebe and @mediaformat ?

**Comment by mediaformat** [comment]
LGTM

**Review by mattwiebe — APPROVED** [review]
Looks good! Hope it'll help us get to the bottom of some problems.

**Pull request merged**
